version: "3"
services:
  registry:
    image: registry:2.8.1
    container_name: registry
    
    volumes:
      - ./htpasswd:/auth/htpasswd
      - ~/docker_registry_data:/var/lib/registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    restart: always
    labels:
      - traefik.http.routers.docker_registry.rule=Host(`registry.meowalien.com`)
      - traefik.http.routers.docker_registry.tls=true
      - traefik.http.routers.docker_registry.tls.options=default
      - traefik.http.routers.docker_registry.tls.certresolver=myresolver
      - traefik.http.routers.docker_registry.entrypoints=websecure
      - traefik.http.services.docker_registry.loadbalancer.server.port=5000

      - traefik.tcp.routers.docker_registry.tls=true
      - traefik.tcp.routers.docker_registry.tls.options=default
      - traefik.tcp.routers.docker_registry.tls.certresolver=myresolver
      - traefik.tcp.routers.docker_registry.entrypoints=websecure
      - traefik.tcp.services.docker_registry.loadbalancer.server.port=5000

networks:
  traefik-net:
    external: true