#version: '3'
#
#services:
#  traefik:
#    image: traefik:v2.9
#    command:
#      - "--api.insecure=true"
#      - "--api.dashboard=true"
#      - "--providers.docker=true"
#      - "--entrypoints.web.address=:80"
#    ports:
#      - "80:80"
#      - "8080:8080"
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"


version: '3'

services:
  traefik:
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./certs/local.key:/certs/key.key"
      - "./certs/local_fullchain.pem:/certs/cert.pem"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.local`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
