version: "3.7"

services:
  deploy:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: always
    
    labels:
      - traefik.http.routers.${CONTAINER_NAME}.rule=Host(`api.meowalien.com`)
      - traefik.http.routers.${CONTAINER_NAME}.tls=true
      - traefik.http.routers.${CONTAINER_NAME}.tls.certresolver=myresolver
      - traefik.http.routers.${CONTAINER_NAME}.tls.options=default
      - traefik.http.routers.${CONTAINER_NAME}.entrypoints=websecure
      - traefik.http.services.${CONTAINER_NAME}.loadbalancer.server.port=3001
networks:
  #  docker network create traefik-net
  traefik-net:
    external: true