// Generated by CoffeeScript 2.5.1
(function() {
  // Initialization code.
  $(document).ready(function() {
    var ENTER_KEY;
    // Initialize global state
    ENTER_KEY = 13;
    $("#serverName").keyup(function(evt) {
      var name;
      if (evt.keyCode === ENTER_KEY) {
        name = $('#serverName').val();
        return window.location.href = "/server/" + name;
      }
    });
    return $(".create-server").click(function(evt) {
      var name, newLink, template;
      name = $('#serverName').val();
      template = $(this).attr("data-tmpl");
      newLink = "/server/" + name + "?template=" + template;
      return this.href = newLink;
    });
  });

}).call(this);
