version: "3"
services:
  registry:
    image: registry:2.8.1
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./auth:/auth
      - ./registry/data:/var/lib/registry
      - /etc/letsencrypt/live/meowalien.com/fullchain.pem:/certs/meowalien.com.crt
      - /etc/letsencrypt/live/meowalien.com/privkey.pem:/certs/meowalien.com.key
#      - ./registry/config.yml:/etc/docker/registry/config.yml
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/meowalien.com.crt
      REGISTRY_HTTP_TLS_KEY: /certs/meowalien.com.key
    restart: always
