version: '3'

services:
  traefik:
    image: traefik:v2.9
    restart: always
    container_name: traefik
    networks:
      - traefik-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/etc/traefik/dynamic.yml
      - ./acme.json:/acme.json
      - ~/traefik_log:/log
    labels:
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.meowalien.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.options=default"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=sayken:$$2y$$05$$iTKM6Fff8ndgV0/OnDmZ9ufk1qljgBkL6KULBd8qX5pQkjT0i8SGG"

networks:
#  docker network create traefik-net
  traefik-net:
    external: true