// Generated by CoffeeScript 2.5.1
(function() {
  ` Backend and view for data surrounding the connections to the server. 

Tracks the count.`;
  window.ServerConnectionDataModel = (function() {
    class ServerConnectionDataModel extends Backbone.Model {};

    ServerConnectionDataModel.prototype.defaults = {
      count: 0
    };

    return ServerConnectionDataModel;

  }).call(this);

  window.ServerConnectionDataView = class ServerConnectionDataView extends Backbone.View {
    initialize(options) {
      this.el = $(this.el);
      this.dataEl = this.el.find(".server-connection-data");
      this.dataEl.html(this.model.get("count")); // Initial display.
      return this.model.on("change:count", (newCount) => {
        return this.dataEl.html(this.model.get("count"));
      });
    }

  };

}).call(this);
