// Generated by CoffeeScript 2.5.1
(function() {
  `Simple wrapper for user sessions.`;
  window.UserSessions = class UserSessions {
    // TODO include secret key.
    constructor() {
      this.addSession = this.addSession.bind(this);
      this.removeSession = this.removeSession.bind(this);
      this.getSession = this.getSession.bind(this);
      this.sessions = {};
      this.randomVal = CryptoJS.lib.WordArray.random(128 / 8); // TODO make it more secure.
      this.hash = CryptoJS.SHA256;
    }

    addSession(sessionId) {
      return this.sessions[this.hash(sessionId + "" + this.randomVal)] = {};
    }

    removeSession(sessionId) {
      return delete this.sessions[this.hash(sessionId + "" + this.randomVal)];
    }

    getSession(sessionId) {
      return this.sessions[this.hash(sessionId + "" + this.randomVal)];
    }

  };

}).call(this);
