// Generated by CoffeeScript 2.5.1
(function() {
  `Simple wrapper for rendering a user-created Handlebars template.

Could be built out in the future by supporting user-created handlebars helpers, etc.`;
  window.UserTemplateRenderer = class UserTemplateRenderer {
    static renderTemplate(source, context) {
      var template;
      template = Handlebars.compile(source);
      return template(context);
    }

  };

}).call(this);
