version: "3.7"

services:
  frontend:
    build: {
        context: .,
        dockerfile: Dockerfile
    }
    image: frontend:latest
    container_name: frontend
    ports:
      - 8080:80
