version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.11.5-management
    container_name: rabbitmq
    volumes:
      - ~/rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq_passwd
    restart: always

    labels:
      - traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.meowalien.com`)
      - traefik.http.routers.rabbitmq.tls=true
      - traefik.http.routers.rabbitmq.tls.certresolver=myresolver
      - traefik.http.routers.rabbitmq.tls.options=default
      - traefik.http.routers.rabbitmq.entrypoints=websecure
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672
