// Generated by CoffeeScript 2.5.1
(function() {
  window.EventTransmitter = class EventTransmitter {
    constructor() {
      this.addEventCallback = this.addEventCallback.bind(this);
      this.sendEvent = this.sendEvent.bind(this);
      this.receiveEvent = this.receiveEvent.bind(this);
      this.eventCallbacks = {};
    }

    addEventCallback(eventName, callback) {
      var eventCallbacks;
      eventCallbacks = this.eventCallbacks[eventName];
      if (!eventCallbacks) {
        eventCallbacks = [];
      }
      eventCallbacks.push(callback);
      return this.eventCallbacks[eventName] = eventCallbacks;
    }

    sendEvent(dataChannel, eventName, data) {
      return dataChannel.send({
        "eventName": eventName,
        "data": data
      });
    }

    receiveEvent(messageEventData) {
      var eventCallback, eventCallbacks, eventName, i, len, messageData, results;
      eventName = messageEventData.eventName;
      messageData = messageEventData.data;
      // console.log("receive event " + eventName, messageData)
      eventCallbacks = this.eventCallbacks[eventName];
      if (eventCallbacks) {
        results = [];
        for (i = 0, len = eventCallbacks.length; i < len; i++) {
          eventCallback = eventCallbacks[i];
          results.push(eventCallback(messageData));
        }
        return results;
      }
    }

  };

}).call(this);
