name: deploy_to_gcp
#run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_HOST:
        required: true
      GOOGLE_CREDENTIALS:
        required: true
jobs:
  deploy_frontend_to_gcp:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    steps:
      - uses: 'actions/checkout@v3'

      - run: echo "IMAGE_NAME_HASH=`echo ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ inputs.IMAGE_NAME }}:${{ env.GIT_SHORT_HASH  }}`" >> $GITHUB_ENV
      - run: echo ${{ env.IMAGE_NAME_HASH }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: "gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- '
                docker pull ${{ env.IMAGE_NAME_HASH }} && \
                docker stop frontend && \
                docker rm frontend && \
                docker run -d -p 80:80 -p 443:443 --name ${{ inputs.IMAGE_NAME }} --restart=always \
                      -v /etc/letsencrypt/live/meowalien.com/fullchain.pem:/certs/meowalien.com.crt \
                      -v /etc/letsencrypt/live/meowalien.com/privkey.pem:/certs/meowalien.com.key \
                      ${{ env.IMAGE_NAME_HASH }}'"