name: deploy
run-name: deploy by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  deploy_to_instance-1:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    steps:
      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: "gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- 'ls -a'"