name: deploy_to_gcp
on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_HOST:
        required: true
      GOOGLE_CREDENTIALS:
        required: true
jobs:
  deploy_frontend_to_gcp:
    concurrency: main
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v3'
      - run: echo "GIT_SHORT_HASH=`echo $(git rev-parse --short HEAD)`" >> $GITHUB_ENV
      - run: echo "FULL_IMAGE_NAME=`echo ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ inputs.IMAGE_NAME }}:${{ env.GIT_SHORT_HASH }}`" >> $GITHUB_ENV
      - run: echo "REMOTE_TEMP_DIR_NAME=`echo /tmp/deploy_frontend_${{ env.GIT_SHORT_HASH }}`" >> $GITHUB_ENV
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
#      - run: "gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- 'cd /home/a_meowalien/deploy/frontend && IMAGE_NAME=${{ env.FULL_IMAGE_NAME }} source ./deploy.sh'"
      - run: "gcloud compute scp --recurse ./deploy/frontend/ a_meowalien@instance-1:${{ env.REMOTE_TEMP_DIR_NAME }} --zone asia-east1-b"
      - run: "gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- 'cd ${{ env.REMOTE_TEMP_DIR_NAME }} && IMAGE_NAME=${{ env.FULL_IMAGE_NAME }} source ./deploy.sh'"

#  gcloud compute scp --recurse ./deploy/frontend/ a_meowalien@instance-1:${{ REMOTE_TEMP_DIR_NAME }}
#  gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- 'cd ${{ REMOTE_TEMP_DIR_NAME }} && IMAGE_NAME=${{ env.FULL_IMAGE_NAME }} source ./deploy.sh'
#gcloud compute scp ./deploy/frontend/ a_meowalien@instance-1:/tmp/deploy_frontend_${{ env.GIT_SHORT_HASH  }} --zone asia-east1-b