name: dev
run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GIT_TAG=`echo ${GITHUB_REF##*/}`" >> $GITHUB_ENV
      - run: echo "IMAGE_NAME=`echo meowalien.com:5000/frontend:${{ env.GIT_TAG }}`" >> $GITHUB_ENV
      - run: echo GIT_TAG is ${{ env.GIT_TAG }}
      - run: echo IMAGE_NAME is ${{ env.IMAGE_NAME }}
  build_frontend:
    depends-on: prepare
#    uses: meowalien/RabbitGather/.github/workflows/build.yaml@main
#    uses: ./.github/workflows/build.yaml
    uses: ./.github/workflows/build.yml
#    with:
    secrets:
      docker_password: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_username: ${{ secrets.DOCKERHUB_TOKEN }}
      image_name: ${{ env.IMAGE_NAME }}
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "GIT_TAG=`echo ${GITHUB_REF##*/}`" >> $GITHUB_ENV
#      - run: echo "IMAGE_NAME=`echo meowalien.com:5000/frontend:${{ env.GIT_TAG }}`" >> $GITHUB_ENV
#      - run: echo GIT_TAG is ${{ env.GIT_TAG }}
#      - run: echo IMAGE_NAME is ${{ env.IMAGE_NAME }}
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: git rev-parse --short HEAD
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          registry: meowalien.com:5000
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          context: ${{ github.workspace }}/frontend/
#          file: ${{ github.workspace }}/frontend/Dockerfile
#          push: true
#          tags: ${{ env.IMAGE_NAME }}

#    runs-on: ubuntu-latest
#    steps:
#    - name: Check out repository code
#      uses: actions/checkout@v3
#    - run: ls -a
#   uses: meowalien/RabbitGather/.github/workflows/build.yaml@main
#   with:
#     config-path: ${{ github.workspace }}/frontend/
#     envPAT: ${{ secrets.DOCKERHUB_TOKEN }}
#     envDOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
#     envGIT_TAG: ${{ github.ref }}
#     envIMAGE_NAME: meowalien.com:5000/frontend:${{ github.ref }}