name: build
run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  build_frontend:
#    - name: Check out repository code
#      uses: actions/checkout@v3
    - run: ls
    - uses: ./.github/workflows/build.yaml@main