name: dev
run-name: push by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'dev'
      - 'main'

jobs:
  build_frontend:
    uses: ./.github/workflows/build.yml
    with:
      IMAGE_NAME: frontend
    secrets:
        DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}



