name: dev
run-name: push by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'dev'
jobs:
  build_frontend:
    uses: ./.github/workflows/build.yml
    with:
      IMAGE_NAME: frontend
    secrets:
        DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}



