name: build
run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  build_frontend:
    uses: meowalien/RabbitGather/.github/workflows/build.yaml@main