name: dev
run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GIT_TAG=`echo ${GITHUB_REF##*/}`" >> $GITHUB_ENV
      - run: echo ${{ env.GIT_TAG }}
      - run: echo "IMAGE_NAME=`echo meowalien.com:5000/frontend:${{ env.GIT_TAG }}`" >> $GITHUB_ENV

    outputs:
      IMAGE_NAME: ${{ env.IMAGE_NAME }}
  build_frontend:
    needs: prepare
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          echo "${{ needs.prepare.outputs.git_tag }}"

    uses: ./.github/workflows/build.yml
    with:
      IMAGE_NAME: ${{ needs.prepare.outputs.IMAGE_NAME }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}