name: build
run-name: build by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  build_frontend:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/build.yaml@main