name: main
run-name: push by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - 'main'
jobs:
  deploy_frontend:
    uses: ./.github/workflows/deploy_to_gcp.yml
    with:
      IMAGE_NAME: frontend
    secrets:
      DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

