name: main
run-name: push by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'

jobs:
  build_frontend:
    uses: ./.github/workflows/build.yml
    with:
      IMAGE_NAME: frontend
    secrets:
      DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  deploy_frontend:
    needs: build_frontend
    uses: ./.github/workflows/deploy_to_gcp.yml
    with:
      IMAGE_NAME: frontend
    secrets:
      DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}


#  deploy_frontend_to_instance-1:
#    runs-on: ubuntu-latest
#    # Add "id-token" with the intended permissions.
#    steps:
#      - uses: 'actions/checkout@v3'
#      - uses: ./.github/workflows/build
#      - id: 'auth'
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
#      - run: "gcloud compute ssh --zone asia-east1-b a_meowalien@instance-1 -- '
#                docker pull meowalien.com:5000/frontend:main && \
#                docker stop frontend && \
#                docker rm frontend && \
#                docker run -d -p 80:80 -p 443:443 --name frontend --restart=always \
#                      -v /etc/letsencrypt/live/meowalien.com/fullchain.pem:/certs/meowalien.com.crt \
#                      -v /etc/letsencrypt/live/meowalien.com/privkey.pem:/certs/meowalien.com.key \
#                      meowalien.com:5000/frontend:main'"