name: on_dev_or_main_push
run-name: push by ${{ github.actor }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'dev'
      - 'main'

jobs:
  build_frontend:
    uses: ./.github/workflow_part/build.yml
    with:
      IMAGE_NAME: frontend
    secrets:
        DOCKER_REGISTRY_HOST: ${{ secrets.DOCKER_REGISTRY_HOST }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
